version: 0.0
os: linux
files:
  - source: /
    destination: /opt/apache-tomcat-8.5.35/webapps
phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/kchange-api.jar
  discard-paths: yes
hooks:
  ApplicationStart:
    - location: /opt/apache-tomcat-8.5.35/bin/startup.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /opt/apache-tomcat-8.5.35/bin/shutdown.sh
      timeout: 300
      runas: root
