version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - /opt/apache-tomcat-8.5.35/webapps/kchange-api.jar
  discard-paths: yes
